name: vibecoderv3
type: gradio-space
sdk: docker

metadata:
  space_id: Chris4K/vibecoderv3
  original_url: https://huggingface.co/spaces/Chris4K/vibecoderv3

deploy:
  targets:
    - public-repo
    - huggingface

build:
  command: bash build.sh

test:
  command: echo "Tests not yet implemented"
